### PR TITLE
feat: enable user sharing

### PR DESCRIPTION
**Pull request by sonle-geekyants**
**- What I did**

[issue atsign-foundation/at_client_sdk#1600](https://github.com/atsign-foundation/at_client_sdk/issues/1600)

**- How I did it**

1. Write data
On Windows, the biometric library is limited to 2560 characters per file.
So when a String is too long, I will split it into a list of strings and save them in files one by one.
2. Read data
When reading data, I will count the total number of files and then merge the contents of the files together.

**- How to verify it**

Check the change code and run the app on Windows.

**- Description for the changelog**

### CODE REVIEW

**Comment by murali-shris** [comment]
@sonle-geekyants please elaborate on the changes.sections how I did, how to verify ?
Please check the feasibility of writing unit tests to verify your code changes.

**Comment by sonle-geekyants** [comment]
I've done the unit test and added the comment for the ticket. Could you please check it? @murali-shris

**Comment by gkc** [comment]
@murali-shris can you review this again please? @sonle-geekyants has made changes in response to your review

**Comment by murali-shris** [comment]
> I've done the unit test and added the comment for the ticket. Could you please check it? @murali-shris

@sonle-geekyants I don't see the unit tests. did you forget to commit ?

**Review by murali-shris — APPROVED** [review]

**Comment by sonle-geekyants** [comment]
No, because my change is private function so I don't write the unit test for it. And I see that now, the unit tests are using functions that have my changes so I thought that if they passed my edits would be correct as well. @murali-shris @gkc

**Pull request merged**
