### PR TITLE
feat: Apkam authorization checks

### LINKED ISSUE #1269: APKAM - namespace authorization for at_client methods
### Is your feature request related to a problem? Please describe.

* For APKAM enrolled apps, there is no authorization check on client side
* keys will be created and will fail in server during sync
* Prevent keys from being created/updated if the enrollment doesn't have authorization

### Describe the solution you'd like

* Implement authorization checks on at_client similar to AbstractVerbHandler authorization check on server
* checks should be implemented got put, get, getKeys, notify methods.
* authorization check should be done for keys with namespace and without namespace

### Describe alternatives you've considered

_No response_

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by murali-shris**
Fixes https://github.com/atsign-foundation/at_client_sdk/issues/1269
- What I did

APKAM authorization checks for local secondary
- How I did it
     - Implemented _isAuthorized method in LocalSecondary similar to the server implementation
_isAuthorized will be called for delete,update, llookup and scan verbs. For other verbs which directly execute on server, _isAuthorized check will be done on server.
     -  _ getEnrollmentDetails() will get the enrollment details for the apkam client from server. Marked a TODO to enhance this impl to read from local secondary in the future
     - added unit tests apkam_authorization_test
- How to verify it

unit tests should pass

### CODE REVIEW

**Comment by murali-shris** [comment]
Tests are currently failing due to this issue.
We are getting enrollment details from server using llookup.
if enrollmentId is set on atClient then server has this check and throws exception
 // Only spp and enroll operations are allowed to access
    // the enrollManageNamespace
    if (keyNamespace == enrollManageNamespace) {
      return (verb is Otp || verb is Enroll)
          ? (access == 'r' || access == 'rw')
          : false;
    }

**Comment by gkc** [comment]
> Tests are currently failing due to this issue. We are getting enrollment details from server using llookup. if enrollmentId is set on atClient then server has this check and throws exception // Only spp and enroll operations are allowed to access // the enrollManageNamespace if (keyNamespace == enrollManageNamespace) { return (verb is Otp || verb is Enroll) ? (access == 'r' || access == 'rw') : false; }

@murali-shris has the issue above been resolved in atServer? If so please link the PR

**Review by gkc — DISMISSED** [review]

**Comment by murali-shris** [comment]
> > Tests are currently failing due to this issue. We are getting enrollment details from server using llookup. if enrollmentId is set on atClient then server has this check and throws exception // Only spp and enroll operations are allowed to access // the enrollManageNamespace if (keyNamespace == enrollManageNamespace) { return (verb is Otp || verb is Enroll) ? (access == 'r' || access == 'rw') : false; }
> 
> @murali-shris has the issue above been resolved in atServer? If so please link the PR

@gkc I am unable to recollect whether the issue I mentioned was fixed at client side or on server. If on server, this must be the PR.
https://github.com/atsign-foundation/at_server/pull/1831

**Comment by sitaram-kalluri** [comment]
Tested the changes with no-ports and working fine. Attaching sshnp log
[sshnp.log](https://github.com/atsign-foundation/at_client_sdk/files/15304794/sshnp.log)

**Review by sitaram-kalluri — APPROVED** [review]

**Comment by gkc** [comment]
@sitaram-kalluri I am seeing failures when running noports e2e tests against the trunk version of at_client and I suspect the failures are related to the APKAM changes. See [this draft PR](https://github.com/atsign-foundation/noports/pull/1112) and [this test run](https://github.com/atsign-foundation/noports/actions/runs/9457492908/job/26051402202?pr=1112)

Looking at the log file you attached above, it looks like in your testing you weren't testing sshnp using APKAM keys 

Please can you run your tests again but running sshnp using APKAM atKeys where the enrollment has namespace access `"sshnp:rw,sshrvd:rw"`

**Comment by gkc** [comment]
@sitaram-kalluri For reference, if you wish to run the noports e2e tests locally then in a clone of the noports repo:
1. modify packages/dart/sshnoports/pubspec.yaml to add a dependency override for at_client
2. run `dart run melos bootstrap` while in the root of the noports repo
3. start up atServers for `@alice` `@bob` and `@chuck` locally
4. run the `buildBinaries` script and run an srvd as `@chuck` : `bin/srvd -a @chuck --root-domain vip.ve.atsign.zone --ip 127.0.0.1`
5. run `tests/e2e_all/scripts/main.sh @alice @bob @chuck -w 5 -r vip.ve.atsign.zone`

**Pull request merged**
