### PR TITLE
Full Regular Expression matching for notificationService.subscribe

### LINKED ISSUE #523: NotificationService does not match regular expressions
**Describe the bug**
Notification Service uses String.allMatches().isNotEmpty which only checks for a match against the exact string.
Something like `.*` will not work with `notificationService.subscribe(regex: '.*')`

**To Reproduce**
1. Call `notificationService.subscribe(regex: '.*${AtEnv.appNamespace}.*')` in an app
2. Send a notification to that atsign
3. And check to see if notifications are received (they aren't)

**Expected behavior**
That regular expressions work for the regex parameter.

**Screenshots**
N/A

**Smartphone (please complete the following information):**
N/A

**Were you using an @‎application when the bug was found?**
N/A

**Additional context**
Opening a PR with a fix using `RegExp().hasMatch()`

### PR DESCRIPTION
**Pull request by xavierchanth**
closes #523 

**- What I did**

- Replaced exact string match (`String.allMatches().isNotEmpty`) with `RegExp().hasMatch()`

**- How I did it**

- Local Changes

**- How to verify it**

**- Description for the changelog**
Full Regular Expression matching for notificationService.subscribe

### CODE REVIEW

**Comment by XavierChanth** [comment]
Waiting for the test secondaries to be updated by shepherd before rerunning the tests.

**Comment by gkc** [comment]
Our cicd test images may be a bit borked, hence test failures. We are investigating.

**Review by gkc — APPROVED** [review]
LGTM. As with all such changes though, some current usages may well depend on the existing incorrect behaviour. Please test accordingly 😀

**Comment by xavierchanth** [comment]
Is something like this suitable proof:
```dart
void main() async {
  String key = '@interiorwolverine:phone.streamprovider@snowboardingbeaver87';
  String regex;

  regex = '@interiorwolverine:phone.streamprovider@snowboardingbeaver87';
  print(originalQuery(regex, key)); // TRUE
  print(newQuery(regex, key)); // TRUE

  regex = 'phone';
  print(originalQuery(regex, key)); // TRUE
  print(newQuery(regex, key)); // TRUE

  regex = 'phone.streamprovider';
  print(originalQuery(regex, key)); // TRUE
  print(newQuery(regex, key)); // TRUE

  regex = '.*phone';
  print(originalQuery(regex, key)); // FALSE
  print(newQuery(regex, key)); // TRUE
}

bool originalQuery(String regex, String key) {
  return regex.allMatches(key).isNotEmpty;
}

bool newQuery(String regex, String key) {
  return RegExp(regex).hasMatch(key);
}
```

The previous only matched for exact string values, which this still does.

Should I implement a test for it somewhere?

**Comment by gkc** [comment]
Ah OK, yeah this is fine. Yes ideally you should add a test somewhere. You could add a few simple unit tests just for this by breaking out the two relevant lines of code into their own method in NotificationServiceImpl and then just writing tests for that method. Or something else - up to you!

**Comment by gkc** [comment]
👍👍 nice

**Comment by gkc** [comment]
@XavierChanth please merge the latest changes from atsign-foundation/at_client_sdk/trunk into your branch ... those changes should resolve the failing checks

**Comment by xavierchanth** [comment]
@gkc Do the CICD credentials need to be updated? It looks like they were 4 days ago.

**Comment by gkc** [comment]
@XavierChanth yep. the move to using a new set of atSigns for testing dedicated to this repo has been a bit painful. I'm just merging those changes into trunk as well now. I'll ping you when done.

**Comment by gkc** [comment]
@XavierChanth all right ... #512 has been merged to trunk. Please merge from this trunk into your trunk again - thanks!

**Comment by xavierchanth** [comment]
Is this an issue with secrets @gkc ?

**Comment by gkc** [comment]
@XavierChanth yes it's a secrets issue. We need to configure the actions so we only run the 'unit tests' check (which also actually includes the functional tests, we need to split it up into two checks) for pull requests from external branches.

**Comment by xavierchanth** [comment]
I see, I could first push to a base branch, then pr to trunk.

**Pull request closed without merging**
