### PR TITLE
fix: keychain store key #468

### PR DESCRIPTION
**Pull request by sonle-geekyants**
**- What I did**
Resolve this issue [#468](https://github.com/atsign-foundation/apps/issues/468)
**- How I did it**

**- How to verify it**

**- Description for the changelog**

### CODE REVIEW

**Review by cpswan — CHANGES_REQUESTED** [review]
.DS_Store is causing a merge conflict, but probably shouldn't be here anyway, and thus should be added to .gitignore.

**Review by cconstab — APPROVED** [review]

**Comment by gkc** [comment]
@sonle-geekyants @sarika01 ping! See @cpswan's request https://github.com/atsign-foundation/at_client_sdk/pull/441#pullrequestreview-906932466

**Comment by sonle-geekyants** [comment]
@gkc okay, I'll check and update it.

**Comment by gkc** [comment]
@sonle-geekyants If this PR is obsolete (e.g. the changes were committed in some other PR), of course just close this one!

**Comment by sonle-geekyants** [comment]
@gkc I got it.
@sarika01 I will close it temporarily and will reopen later

**Pull request closed without merging**
