### PR TITLE
feat: bypass cache option in get method

### PR DESCRIPTION
**Pull request by murali-shris**
**- What I did**
 * added a feature to bypass cache in at client get method
**- How I did it**
* introduced a new class GetRequestOptions with byPassCache attribute
* Added GetRequestOptions as optional param to at client get method
* modified GetRequestTransformer and PutRequestTransformer
* introduced new abstract class RequestTransformer which extends Transformer and adds an optional RequestOptions
**- How to verify it**
* Run the group of  tests - "A group of tests to check bypass cache flag" in verb_builder_test.dart

### CODE REVIEW

**Comment by murali-shris** [comment]
checking the test failures

**Review by sitaram-kalluri — APPROVED** [review]

**Comment by murali-shris** [comment]
> checking the test failures



> checking the test failures



> checking the test failures

fixed

**Review by gkc — CHANGES_REQUESTED** [review]
This is a bit nit-picky, but please change all variable names which have 'byPass' to 'bypass' as bypass is the actual word

e.g. in GetRequestOptions, the bool should be `bypassCache` rather than `byPassCache`

**Comment by murali-shris** [comment]
> This is a bit nit-picky, but please change all variable names which have 'byPass' to 'bypass' as bypass is the actual word
> 
> e.g. in GetRequestOptions, the bool should be `bypassCache` rather than `byPassCache`

changes done

**Review by gkc — APPROVED** [review]

**Pull request merged**
