### PR TITLE
fix: Failing E2E test - verify cached key is deleted in sharedWith secondary when CCD is set to true

### LINKED ISSUE #1015: End to end tests failing for spurious reasons
### Describe the bug

Presents similar problems to #994 

https://github.com/atsign-foundation/at_client_sdk/actions/runs/4868758186 provides an example where the first run of `end2end_tests` completed with `36 tests passed, 1 failed.` then the second run `end2end_test_14` completed with `36 tests passed, 1 failed.` then third time lucky and the tests pass.

The test that seems to cause the problems is:

```
test/deletion_key_test.dart: A test to verify cached key is deleted in sharedWith secondary when CCD is set to true (failed)
```

### Steps to reproduce

1. First I merge a Dependabot PR that's unrelated to the test surface area
2. Then the full test suite runs
3. And then the end2end tests fail when they shouldn't

### Expected behavior

Tests should pass when merging changes that don't affect the test path

### PR DESCRIPTION
**Pull request by purnimavenkatasubbu**
**- What I did**
Fix the following end2end test:
  * A test to verify cached key is deleted in sharedWith secondary when CCD is set to true

Root-Cause of the issue:
* On the sender's client, when a key is updated/deleted with a TTR set, a cached key gets created on the secondary server of the sharedWith atSign (receiver). 
* On the receiver's client, we check if a cached key is synced from the receiver's secondary server. The test fails because the assertions happen before the key gets synced to the receiver's client.
  
**- How I did it**

* Enhance the E2ESyncService follows:
   *  Run the sync service until localCommitId and serverCommitId are equal.
   *  But the above check alone would not suffice because, at the moment, the sync process waits until the client and server are in sync. But yet times, the client and server will be in sync when "test" runs the sync and then the cached key gets created in cloud secondary and  syncs to the client. 
   * To fix the above, an optional parameter - SyncOptions, is added to the syncData method in the E2ESyncService. 
   * The SyncOptions has a key of type String, when populated, the E2ESyncService waits until the key is synced to the client

**- How to verify it**
* All the e2e tests should pass

Pending-Work:
* Currently, SyncOptions has only a "key" field. There might be a need to wait for a specific key with a particular CommitOp. 
* For example, let's imagine the following scenario:
   * A key - "phone.wavi" is updated and then deleted and we have an assertion of "phone.wavi" with CommitOp.Delete.
   * The SyncService, sync only the CommitOp.Update, but yet to Sync "CommitOp.Delete". If an assertion happens at this point, the test will fail.

### CODE REVIEW

**Review by gkc — DISMISSED** [review]
LGTM

**Comment by gkc** [comment]
Hi @purnimavenkatasubbu @sitaram-kalluri a test failed again in an [actions run](https://github.com/atsign-foundation/at_client_sdk/actions/runs/4892434190/jobs/8734257599?pr=1021) just now on this PR

```
❌ test/deletion_key_test.dart: A test to verify cached key is deleted in sharedWith secondary when CCD is set to true (failed)
  INFO|2023-05-05 10:34:34.010123|AtLookup|Creating new connection 
  
  INFO|2023-05-05 10:34:34.152622|AtLookup|New connection created OK 
  
  INFO|2023-05-05 10:34:34.268378|AtLookup|auth success 
  
  INFO|2023-05-05 10:34:34.323468|SyncService (@ce2e4)|159428760|Returning serverCommitId 312098 
  
  INFO|2023-05-05 10:34:34.329379|SyncService (@ce2e4)|159428760|Inside syncComplete. syncRequest.requestSource : SyncRequestSource.app; syncRequest.onDone : null 
  
  Exception: cached:@ce2e4:deletecachedkey.wavi@ce2e1 does not exist in keystore
  package:at_client/src/client/at_client_impl.dart 341:7  AtClientImpl.get
```

**Comment by purnimavenkatasubbu** [comment]
> Hi @purnimavenkatasubbu @sitaram-kalluri a test failed again in an [actions run](https://github.com/atsign-foundation/at_client_sdk/actions/runs/4892434190/jobs/8734257599?pr=1021) just now on this PR
> 
> ```
> ❌ test/deletion_key_test.dart: A test to verify cached key is deleted in sharedWith secondary when CCD is set to true (failed)
>   INFO|2023-05-05 10:34:34.010123|AtLookup|Creating new connection 
>   
>   INFO|2023-05-05 10:34:34.152622|AtLookup|New connection created OK 
>   
>   INFO|2023-05-05 10:34:34.268378|AtLookup|auth success 
>   
>   INFO|2023-05-05 10:34:34.323468|SyncService (@ce2e4)|159428760|Returning serverCommitId 312098 
>   
>   INFO|2023-05-05 10:34:34.329379|SyncService (@ce2e4)|159428760|Inside syncComplete. syncRequest.requestSource : SyncRequestSource.app; syncRequest.onDone : null 
>   
>   Exception: cached:@ce2e4:deletecachedkey.wavi@ce2e1 does not exist in keystore
>   package:at_client/src/client/at_client_impl.dart 341:7  AtClientImpl.get
> ```

Looking at it.

**Comment by sitaram-kalluri** [comment]
> Hi @purnimavenkatasubbu @sitaram-kalluri a test failed again in an [actions run](https://github.com/atsign-foundation/at_client_sdk/actions/runs/4892434190/jobs/8734257599?pr=1021) just now on this PR
> 
> ```
> ❌ test/deletion_key_test.dart: A test to verify cached key is deleted in sharedWith secondary when CCD is set to true (failed)
>   INFO|2023-05-05 10:34:34.010123|AtLookup|Creating new connection 
>   
>   INFO|2023-05-05 10:34:34.152622|AtLookup|New connection created OK 
>   
>   INFO|2023-05-05 10:34:34.268378|AtLookup|auth success 
>   
>   INFO|2023-05-05 10:34:34.323468|SyncService (@ce2e4)|159428760|Returning serverCommitId 312098 
>   
>   INFO|2023-05-05 10:34:34.329379|SyncService (@ce2e4)|159428760|Inside syncComplete. syncRequest.requestSource : SyncRequestSource.app; syncRequest.onDone : null 
>   
>   Exception: cached:@ce2e4:deletecachedkey.wavi@ce2e1 does not exist in keystore
>   package:at_client/src/client/at_client_impl.dart 341:7  AtClientImpl.get
> ```

Below is the hypothesis on why the test is still failing.

With these code changes, we are waiting until the client and server are in sync. But we might have a possibility that after the test has verified for the client and server are in sync and moved forward, the cached key arrives into the cloud secondary.
   * One approach to fix this is to add an optional parameter "String key" into the E2ESyncService.syncData in the E2E test. So, that we can wait for a particular key to sync into the client and then perform assertions. 

Will continue to work on this to find the other potential causes and approaches to fix them.

**Comment by sitaram-kalluri** [comment]
> > Hi @purnimavenkatasubbu @sitaram-kalluri a test failed again in an [actions run](https://github.com/atsign-foundation/at_client_sdk/actions/runs/4892434190/jobs/8734257599?pr=1021) just now on this PR
> > ```
> > ❌ test/deletion_key_test.dart: A test to verify cached key is deleted in sharedWith secondary when CCD is set to true (failed)
> >   INFO|2023-05-05 10:34:34.010123|AtLookup|Creating new connection 
> >   
> >   INFO|2023-05-05 10:34:34.152622|AtLookup|New connection created OK 
> >   
> >   INFO|2023-05-05 10:34:34.268378|AtLookup|auth success 
> >   
> >   INFO|2023-05-05 10:34:34.323468|SyncService (@ce2e4)|159428760|Returning serverCommitId 312098 
> >   
> >   INFO|2023-05-05 10:34:34.329379|SyncService (@ce2e4)|159428760|Inside syncComplete. syncRequest.requestSource : SyncRequestSource.app; syncRequest.onDone : null 
> >   
> >   Exception: cached:@ce2e4:deletecachedkey.wavi@ce2e1 does not exist in keystore
> >   package:at_client/src/client/at_client_impl.dart 341:7  AtClientImpl.get
> > ```
> 
> Below is the hypothesis on why the test is still failing.
> 
> With these code changes, we are waiting until the client and server are in sync. But we might have a possibility that after the test has verified for the client and server are in sync and moved forward, the cached arrived in the cloud secondary.
> 
> * One approach to fix this is to add an optional parameter "String key" into the E2ESyncService.syncData in the E2E test. So, that we can wait for a particular key to sync into the client and then perform assertions.
> 
> Will continue to work on this to find the other potential causes and approaches to fix them.

Below are the log snippets to prove the above hypothesis:

```
Client Log - ce2e2
------------------
SyncService| SyncProgress{atSign: @ce2e2, syncStatus: SyncStatus.success, isInitialSync: false, startedAt: 2023-05-07 05:23:53.001031Z, completedAt: 2023-05-07 05:23:53.468138Z, message: null, keyInfoList:null, localCommitIdBeforeSync:null, localCommitId:null, serverCommitId:null***
Completed sync| SyncStatus.success | localCommitId: null | ServerCommitId: null
INFO|2023-05-07 05:24:22.833899|Monitor (@ce2e2)|starting monitor for @ce2e2 with lastNotificationTime: 1683437033843 
  
  Exception: cached:@ce2e2:deletecachedkey.wavi@ce2e1 does not exist in keystore


Server Log - ce2e2
-------------------
ce2e2_secondary.1.fnykmmh3bw1s@cicd2x64    | INFO|2023-05-07 05:24:24.928552|InboundListener|615793957|520731550|RCVD: sync:from:305575:limit:10| 
ce2e2_secondary.1.fnykmmh3bw1s@cicd2x64    | 
ce2e2_secondary.1.fnykmmh3bw1s@cicd2x64    | INFO|2023-05-07 05:24:24.931124|InboundConnectionImpl|615793957|520731550|SENT: data:[{"atKey":"cached:@ce2e2:deletecache
dkey.wavi@ce2e1","value":"m2XnJ3zkXFFIbU8R/f48hP2UFTLtE9AtT+9lRcSr2jg=","metadata":{"createdBy":"@ce2e2","updatedBy":"@ce2e2","createdAt":"2023-05-07 05:23:53.843Z","
updatedAt":"2023-05-07 05:24:23.680Z","availableAt":"2023-05-07 05:24:23.680Z","status":"active","version":"1","ttl":"0","ttb":"0","ttr":"-1","ccd":"true","isEncrypte
d":"true","sharedKeyEnc":"iCEIxBDe5jXvoyMRHoR9QpyKX1zFr1O6WuiILQEV568TZ0DexkE0nF6GgXYu6pRC7UT0zC4uApOlPzL78daDnfiEUMckQsnhivvWlvmDn4dqGfr7ZSsI2aYmlN4DoIiRPy4BUx3uBOVU
5eE9aznLw7R9t2ll/H+PFxGjiwAaLjFxsWTw4dROuKHJF9RvuHxanAEyRxmAOm4cUr33+GTg2BqrPXNKH24Y1wgzbwyNUug+24atVlmbKngVcWFJgCrG0nldPgpiKSCKzO7MarbHEH8FQ5MfCqJgAInOZokrOiz1Zzx2fl
dx2vyZ6ZgS7nN2eOhP8+QU+MMa418q269zJw==","pubKeyCS":"70984cc0ea4d3ba974ee2682c0979d20"},"commitId":305577,"operation":"*"}
```

On the client side, the get request was executed at "2023-05-07 05:23:53", but the key was synced at "2023-05-07 05:24:24"

**Comment by sitaram-kalluri** [comment]
After the fix, log snippet from test, On client side, sync waits for the specific key to sync. Tests pass.

```
INFO|2023-05-07 08:05:48.493581|E2ESyncService|SyncService| SyncProgress{atSign: @ce2e2, syncStatus: SyncStatus.success, isInitialSync: false, startedAt: 2023-05-07 08:05:48.001210Z, completedAt: 2023-05-07 08:05:48.493514Z, message: null, keyInfoList:null, localCommitIdBeforeSync:null, localCommitId:null, serverCommitId:null*** 
INFO|2023-05-07 08:05:48.493761|E2ESyncService|Found SyncOptions...Waiting until the cached:@ce2e2:deletecachedkey.wavi@ce2e1 is synced to client 
INFO|2023-05-07 08:05:49.256190|E2ESyncService|SyncService| SyncProgress{atSign: @ce2e2, syncStatus: SyncStatus.success, isInitialSync: false, startedAt: 2023-05-07 08:05:49.001189Z, completedAt: 2023-05-07 08:05:49.256119Z, message: null, keyInfoList:[KeyInfo{key: cached:@ce2e2:deletecachedkey.wavi@ce2e1, syncDirection: SyncDirection.remoteToLocal , conflictInfo: null, commitOp: CommitOp.UPDATE_ALL***], localCommitIdBeforeSync:305688, localCommitId:305689, serverCommitId:305689*** 
INFO|2023-05-07 08:05:49.256243|E2ESyncService|Found SyncOptions...Waiting until the cached:@ce2e2:deletecachedkey.wavi@ce2e1 is synced to client 
INFO|2023-05-07 08:05:49.256308|E2ESyncService|KeyInfo{key: cached:@ce2e2:deletecachedkey.wavi@ce2e1, syncDirection: SyncDirection.remoteToLocal , conflictInfo: null, commitOp: CommitOp.UPDATE_ALL*** 
INFO|2023-05-07 08:05:49.256356|E2ESyncService|Found cached:@ce2e2:deletecachedkey.wavi@ce2e1 in key list info | SyncStatus.success | localCommitId: 305689 | ServerCommitId: 305689 
```

**Review by gkc — APPROVED** [review]

**Pull request merged**
