### PR TITLE
fix: getAtSign return null

### PR DESCRIPTION
**Pull request by sonle-geekyants**
**- What I did**
Fix this minor issue [#656](https://github.com/atsign-foundation/at_client_sdk/issues/656)

**- How I did it**
Have a mistake in return condition of `getAtSign` in `KeychainManager`.
I corrected it.

**- How to verify it**
Check the code change and verify in the app

**- Description for the changelog**

### CODE REVIEW

**Review by yahu1031 — DISMISSED** [review]
LGTM

**Review by sachins-geekyants — DISMISSED** [review]

**Comment by sonle-geekyants** [comment]
@sachins-geekyants could you please merge and release a new version for this?

**Review by murali-shris — APPROVED** [review]

**Review by murali-shris — CHANGES_REQUESTED** [review]
is it possible to unit test keychain_manager --> getAtSign method?

**Comment by yahu1031** [comment]
It does work for me in mobile currently I'm using this change for atBuzz.

**Comment by gkc** [comment]
@sonle-geekyants @sachins-geekyants Why was this never merged? Is there still a bug here?

**Comment by yahu1031** [comment]
@gkc This used to work sometimes. Not sure why but when I use a debugger, It used to work fine, else it gives me null data. Maybe somewhere an await was missing or something, but before it gets the value, it is getting returned. I tested this branch during that time. My comment from above was during some scenarios and I thought it was working and then later it doesn't. We had a call regarding this. And later never heard about it.

- This info may help for cross-checking things. Regards 😄

**Comment by sachins-geekyants** [comment]
It should have been merged but somehow got missed.
@sonle-geekyants can you check if this PR is still relevant and resolves the conflict?

**Comment by sonle-geekyants** [comment]
Yes, I've checked it, please merge it. @sachins-geekyants

**Review by gkc — DISMISSED** [review]
Per @murali-shris's [request on Sep 14 2022](https://github.com/atsign-foundation/at_client_sdk/pull/662#pullrequestreview-1107056370) please can you create a test which asserts the behaviour of getAtSign

**Review by murali-shris — APPROVED** [review]

**Pull request merged**
