### PR TITLE
ci: Use Docker Compose v2

### PR DESCRIPTION
**Pull request by cpswan**
Fixes https://github.com/atsign-foundation/operations/issues/134 for this repo

**- What I did**

Modified scripts to use Docker Compose v2

**- How I did it**

s/docker-compose/docker compose/

**- How to verify it**

Functional tests

**- Description for the changelog**

ci: Use Docker Compose v2

### CODE REVIEW

**Comment by cpswan** [comment]
More joy - it seems that `test_virtualenv_1` has been automangled to `test-virtualenv-1`

**Comment by gkc** [comment]
@cpswan  I see `Container test-virtualenv-1  Started` in the "Start docker instance" job and `No such container: test_virtualenv_1` in the "Run PKAM" job of the "functional_tests" workflow ([link to action run](https://github.com/atsign-foundation/at_client_sdk/actions/runs/8537827095/job/23389213901?pr=1282))

Perhaps a backwards compatibility issue where previously underscores and hyphens were somehow treated the same way?

**Comment by gkc** [comment]
> @cpswan I see `Container test-virtualenv-1 Started` in the "Start docker instance" job and `No such container: test_virtualenv_1` in the "Run PKAM" job of the "functional_tests" workflow ([link to action run](https://github.com/atsign-foundation/at_client_sdk/actions/runs/8537827095/job/23389213901?pr=1282))
> 
> Perhaps a backwards compatibility issue where previously underscores and hyphens were somehow treated the same way?

( I see you've already fixed it )

**Comment by gkc** [comment]
functional test run (beta) is good but the (stable) run looks like it's going to fail for an unrelated flakiness issue. Will re-run when it does

**Review by gkc — APPROVED** [review]

**Comment by gkc** [comment]
> functional test run (beta) is good but the (stable) run looks like it's going to fail for an unrelated flakiness issue. Will re-run when it does

Didn't fail but took twice as long as the (beta) run. I'll copy the test run logs to take a look later if I have time.

**Pull request merged**
