### PR TITLE
fix: force pull for docker-compose in functional tests

### PR DESCRIPTION
**Pull request by cpswan**
**- What I did**

added `docker-compose pull` before bringing `up`

Also added `coverage/` directory to .gitignore

**- Description for the changelog**

fix: force pull for docker-compose in functional tests
fix: add coverage directory to .gitignore

### CODE REVIEW

**Review by gkc — DISMISSED** [review]

**Comment by cpswan** [comment]
This definitely pulled the latest image, but there are still certificate problems in the Actions run:

```
SEVERE|2022-09-26 13:48:01.709287|AtLookup|Error in remote verb execution Exception: HandshakeException: Handshake error in client (OS Error: 
	CERTIFICATE_VERIFY_FAILED: unable to get local issuer certificate(handshake.cc:393)) 
```

**Review by sitaram-kalluri — DISMISSED** [review]

**Comment by cpswan** [comment]
Converted to Draft, as this isn't ready to be merged.

My next steps:

1, Alter workflow to echo cacerts, and verify that's carrying expected root CA
2. Alter workflow to incorporate certinfo, and use that to check certs being presented by the virtualenv

**Comment by cpswan** [comment]
@kalluriramkumar I think this should still be merged, but the functional tests are still failing as before (#721) with cert errors. Any thoughts on why that might be happening?

**Comment by gkc** [comment]
@cpswan your branch is a few commits behind trunk and needs to have those commits merged in in order for the tests to pass

**Comment by cpswan** [comment]
@gkc of course 🤦 though previously I've seen a helpful button to press to catch up :/

**Comment by gkc** [comment]
> @gkc of course 🤦 though previously I've seen a helpful button to press to catch up :/

Yes I haven't quite figured out why sometimes that button is there and sometimes it isn't 🤔 ... it is very annoying when it isn't there, and yes I've been bitten by this in the past 😬

**Review by gkc — APPROVED** [review]

**Pull request merged**
